/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cruz.mx.views;

import com.cruz.mx.beans.Concepto;
import com.cruz.mx.beans.Retencion;
import com.cruz.mx.beans.Traslado;
import com.cruz.mx.business.AbstractConcepto;
import com.cruz.mx.business.AbstractRetenciones;
import com.cruz.mx.business.AbstractTraslados;
import com.cruz.mx.business.LoadProperties;
import com.cruz.mx.business.ProcesarXML;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import javax.swing.Action;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.log4j.Logger;
import org.apache.tools.ant.DirectoryScanner;

/**
 *
 * @author acruzb
 */
public class Principal extends javax.swing.JFrame {

    private static final Logger LOGGER = Logger.getLogger(Principal.class);
    private final AbstractConcepto modelConceptos;
    private final AbstractRetenciones modelRetenciones;
    private final AbstractTraslados modelTraslados;
    
    private DialogArchivosCarpeta dialogArchivos;
    
    public final static String XML_FORMAT = ".xml";
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        LOGGER.info("Iniciando aplicación.");
        init();
        centrarVista();
        modelConceptos = new AbstractConcepto();
        this.tablaConceptos.setModel(modelConceptos);
        this.tablaConceptos.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        modelRetenciones = new AbstractRetenciones();
        this.tablaRetenciones.setModel(modelRetenciones);
        this.tablaRetenciones.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        modelTraslados = new AbstractTraslados();
        this.tablaTraslados.setModel(modelTraslados);
        this.tablaTraslados.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        
        dialogArchivos = new DialogArchivosCarpeta(this, false, this);
        dialogArchivos.setLocationRelativeTo(this);
        dialogArchivos.addWindowListener(new WindowAdapter(){
          @Override
          public void windowClosed(WindowEvent e){
//              dialogArchivos.empty();
          }
          @Override
          public void windowClosing(WindowEvent e){
//              dialogArchivos.empty();
          }
        });
    }

    public final void init(){
        this.setIconImage(new ImageIcon(getClass().getClassLoader().getResource("images/logo.png")).getImage());
    }
    
    public final void centrarVista(){
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        setTitle("Verificador de XML " + LoadProperties.PROPS.get("version"));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelInfoGeneral = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        texttipoDeComprobante = new javax.swing.JTextField();
        textdescuento = new javax.swing.JTextField();
        textTipoCambio = new javax.swing.JTextField();
        textMontoFolioFiscalOrig = new javax.swing.JTextField();
        textLugarExpedicion = new javax.swing.JTextField();
        textcondicionesDePago = new javax.swing.JTextField();
        textFolioFiscalOrig = new javax.swing.JTextField();
        textSerieFolioFiscalOrig = new javax.swing.JTextField();
        textFechaFolioFiscalOrig = new javax.swing.JTextField();
        labelVersion = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        textserie = new javax.swing.JTextField();
        textfolio = new javax.swing.JTextField();
        textfecha = new javax.swing.JTextField();
        textformaDePago = new javax.swing.JTextField();
        textmetodoDePago = new javax.swing.JTextField();
        textMoneda = new javax.swing.JTextField();
        textsubTotal = new javax.swing.JTextField();
        texttotal = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelEmisor = new javax.swing.JPanel();
        panelInfoEmisor = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        textNombreEmisor = new javax.swing.JTextField();
        textRFCEmisor = new javax.swing.JTextField();
        panelDomFiscal = new javax.swing.JPanel();
        textCalleF = new javax.swing.JTextField();
        textNumExtF = new javax.swing.JTextField();
        textColoniaF = new javax.swing.JTextField();
        textLocalidadF = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        textCPF = new javax.swing.JTextField();
        textMunicipioF = new javax.swing.JTextField();
        textEstadoF = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        textPaisF = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        panelExpedidoEn = new javax.swing.JPanel();
        textCalleEx = new javax.swing.JTextField();
        textNumExtEx = new javax.swing.JTextField();
        textColoniaEx = new javax.swing.JTextField();
        textLocalidadEx = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        textCPEx = new javax.swing.JTextField();
        textMunicipioEx = new javax.swing.JTextField();
        textEstadoEx = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        textPaisEx = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        textRegimenEmisor = new javax.swing.JTextField();
        panelInfoReceptor = new javax.swing.JPanel();
        panelReceptor = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        panelDomReceptor = new javax.swing.JPanel();
        textCalleR = new javax.swing.JTextField();
        textNumExtR = new javax.swing.JTextField();
        textColoniaR = new javax.swing.JTextField();
        textLocalidadR = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        textCPR = new javax.swing.JTextField();
        textMunicipioR = new javax.swing.JTextField();
        textEstadoR = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        textPaisR = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        textRFCReceptor = new javax.swing.JTextField();
        textNombreReceptor = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        panelInfoConceptos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaConceptos = new javax.swing.JTable();
        jLabel44 = new javax.swing.JLabel();
        panelInfoImpuestos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaTraslados = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaRetenciones = new javax.swing.JTable();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        textTotalRetenciones = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        textTotalTraslados = new javax.swing.JTextField();
        panelInfoComplemento = new javax.swing.JPanel();
        panelComplemento = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        textUuid = new javax.swing.JTextField();
        textFechaTimbrado = new javax.swing.JTextField();
        textSelloCFD = new javax.swing.JTextField();
        textCertSAT = new javax.swing.JTextField();
        textSelloSAT = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuSeleccionarArchivo = new javax.swing.JMenuItem();
        menuSeleccionarCarpeta = new javax.swing.JMenuItem();
        menuListarArchivos = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenu();
        menuLimpiar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelInfoGeneral.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Versión");

        jLabel2.setText("Serie");

        jLabel3.setText("Folio");

        jLabel4.setText("Fecha");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Forma de pago");

        jLabel6.setText("Método de pago");

        jLabel7.setText("Tipo de cambio");

        jLabel8.setText("Descuento");

        jLabel9.setText("Total");

        jLabel10.setText("Lugar de expefición");

        jLabel11.setText("Condiciones de pago");

        jLabel12.setText("Monto folio fiscal ori");

        jLabel13.setText("Subtotal");

        jLabel14.setText("Folio fiscal original");

        jLabel15.setText("Serie folio fiscal original");

        jLabel16.setText("Fecha folio fiscal original");

        texttipoDeComprobante.setEditable(false);

        textdescuento.setEditable(false);

        textTipoCambio.setEditable(false);

        textMontoFolioFiscalOrig.setEditable(false);

        textLugarExpedicion.setEditable(false);

        textcondicionesDePago.setEditable(false);

        textFolioFiscalOrig.setEditable(false);

        textSerieFolioFiscalOrig.setEditable(false);

        textFechaFolioFiscalOrig.setEditable(false);

        labelVersion.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        labelVersion.setText("0.0");

        jLabel17.setText("Tipo de comprobante");

        jLabel18.setText("Moneda");

        textserie.setEditable(false);

        textfolio.setEditable(false);

        textfecha.setEditable(false);

        textformaDePago.setEditable(false);

        textmetodoDePago.setEditable(false);

        textMoneda.setEditable(false);

        textsubTotal.setEditable(false);

        texttotal.setEditable(false);

        javax.swing.GroupLayout panelInfoGeneralLayout = new javax.swing.GroupLayout(panelInfoGeneral);
        panelInfoGeneral.setLayout(panelInfoGeneralLayout);
        panelInfoGeneralLayout.setHorizontalGroup(
            panelInfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelVersion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addGroup(panelInfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6)
                    .addComponent(jLabel17))
                .addGap(15, 15, 15)
                .addGroup(panelInfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(textmetodoDePago, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textformaDePago, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textfecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textserie, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(textfolio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(texttipoDeComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelInfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12)
                    .addComponent(jLabel18)
                    .addComponent(jLabel13)
                    .addComponent(jLabel9))
                .addGap(15, 15, 15)
                .addGroup(panelInfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textTipoCambio)
                    .addComponent(textdescuento)
                    .addComponent(textMontoFolioFiscalOrig)
                    .addComponent(textMoneda, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(textsubTotal)
                    .addComponent(texttotal))
                .addGap(18, 18, 18)
                .addGroup(panelInfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel10))
                .addGap(15, 15, 15)
                .addGroup(panelInfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textLugarExpedicion)
                    .addComponent(textcondicionesDePago)
                    .addComponent(textFolioFiscalOrig)
                    .addComponent(textSerieFolioFiscalOrig)
                    .addComponent(textFechaFolioFiscalOrig, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        panelInfoGeneralLayout.setVerticalGroup(
            panelInfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoGeneralLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelInfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoGeneralLayout.createSequentialGroup()
                        .addGroup(panelInfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(textserie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(textTipoCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)
                                .addComponent(textLugarExpedicion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(5, 5, 5)
                        .addGroup(panelInfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(textfolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(textdescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(textcondicionesDePago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(panelInfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel12)
                            .addComponent(textMontoFolioFiscalOrig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(textFolioFiscalOrig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(panelInfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textformaDePago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel18)
                            .addComponent(textMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(textSerieFolioFiscalOrig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(panelInfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textmetodoDePago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel13)
                            .addComponent(textsubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(textFechaFolioFiscalOrig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelInfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(texttipoDeComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel9)
                            .addComponent(texttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelInfoGeneralLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(labelVersion))
                    .addGroup(panelInfoGeneralLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelInfoEmisor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Emisor");

        jLabel22.setText("Nombre");

        jLabel23.setText("RFC");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setText("Domicilio fiscal");

        textNombreEmisor.setEditable(false);

        textRFCEmisor.setEditable(false);

        textCalleF.setEditable(false);

        textNumExtF.setEditable(false);

        textColoniaF.setEditable(false);

        textLocalidadF.setEditable(false);

        jLabel31.setText("Calle");

        jLabel27.setText("Núm Ext");

        jLabel32.setText("Colonia");

        jLabel25.setText("Localidad");

        jLabel26.setText("CP");

        textCPF.setEditable(false);

        textMunicipioF.setEditable(false);

        textEstadoF.setEditable(false);

        jLabel30.setText("Municipio");

        jLabel28.setText("Estado");

        jLabel29.setText("País");

        textPaisF.setEditable(false);

        javax.swing.GroupLayout panelDomFiscalLayout = new javax.swing.GroupLayout(panelDomFiscal);
        panelDomFiscal.setLayout(panelDomFiscalLayout);
        panelDomFiscalLayout.setHorizontalGroup(
            panelDomFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDomFiscalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDomFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(jLabel25)
                    .addComponent(jLabel28)
                    .addComponent(jLabel26)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelDomFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDomFiscalLayout.createSequentialGroup()
                        .addComponent(textCalleF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textNumExtF, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textColoniaF)
                    .addComponent(textLocalidadF)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDomFiscalLayout.createSequentialGroup()
                        .addComponent(textCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textMunicipioF, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDomFiscalLayout.createSequentialGroup()
                        .addComponent(textEstadoF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textPaisF, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelDomFiscalLayout.setVerticalGroup(
            panelDomFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDomFiscalLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(panelDomFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCalleF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel27)
                    .addComponent(textNumExtF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(panelDomFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textColoniaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addGap(5, 5, 5)
                .addGroup(panelDomFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLocalidadF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(5, 5, 5)
                .addGroup(panelDomFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addGroup(panelDomFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel30)
                        .addComponent(textMunicipioF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addGroup(panelDomFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDomFiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textEstadoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel29)
                        .addComponent(textPaisF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel28))
                .addGap(27, 27, 27))
        );

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel41.setText("Expedido en");

        textCalleEx.setEditable(false);

        textNumExtEx.setEditable(false);

        textColoniaEx.setEditable(false);

        textLocalidadEx.setEditable(false);

        jLabel63.setText("Calle");

        jLabel64.setText("Núm Ext");

        jLabel65.setText("Colonia");

        jLabel66.setText("Localidad");

        jLabel67.setText("CP");

        textCPEx.setEditable(false);

        textMunicipioEx.setEditable(false);

        textEstadoEx.setEditable(false);

        jLabel68.setText("Municipio");

        jLabel69.setText("Estado");

        jLabel70.setText("País");

        textPaisEx.setEditable(false);

        javax.swing.GroupLayout panelExpedidoEnLayout = new javax.swing.GroupLayout(panelExpedidoEn);
        panelExpedidoEn.setLayout(panelExpedidoEnLayout);
        panelExpedidoEnLayout.setHorizontalGroup(
            panelExpedidoEnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExpedidoEnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelExpedidoEnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel65)
                    .addComponent(jLabel66)
                    .addComponent(jLabel69)
                    .addComponent(jLabel67)
                    .addComponent(jLabel63))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelExpedidoEnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelExpedidoEnLayout.createSequentialGroup()
                        .addComponent(textCalleEx)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel64)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textNumExtEx, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textColoniaEx)
                    .addComponent(textLocalidadEx)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelExpedidoEnLayout.createSequentialGroup()
                        .addComponent(textCPEx, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel68, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textMunicipioEx, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelExpedidoEnLayout.createSequentialGroup()
                        .addComponent(textEstadoEx)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel70)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textPaisEx, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelExpedidoEnLayout.setVerticalGroup(
            panelExpedidoEnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelExpedidoEnLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(panelExpedidoEnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCalleEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel63)
                    .addComponent(jLabel64)
                    .addComponent(textNumExtEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(panelExpedidoEnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textColoniaEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel65))
                .addGap(5, 5, 5)
                .addGroup(panelExpedidoEnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLocalidadEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel66))
                .addGap(5, 5, 5)
                .addGroup(panelExpedidoEnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel67)
                    .addGroup(panelExpedidoEnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textCPEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel68)
                        .addComponent(textMunicipioEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addGroup(panelExpedidoEnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelExpedidoEnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textEstadoEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel70)
                        .addComponent(textPaisEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel69))
                .addGap(27, 27, 27))
        );

        jLabel43.setText("Régimen");

        textRegimenEmisor.setEditable(false);

        javax.swing.GroupLayout panelInfoEmisorLayout = new javax.swing.GroupLayout(panelInfoEmisor);
        panelInfoEmisor.setLayout(panelInfoEmisorLayout);
        panelInfoEmisorLayout.setHorizontalGroup(
            panelInfoEmisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoEmisorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoEmisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addGroup(panelInfoEmisorLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel24)
                        .addGap(390, 390, 390)
                        .addComponent(jLabel41))
                    .addGroup(panelInfoEmisorLayout.createSequentialGroup()
                        .addComponent(panelDomFiscal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(panelExpedidoEn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInfoEmisorLayout.createSequentialGroup()
                        .addGroup(panelInfoEmisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addGroup(panelInfoEmisorLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(57, 57, 57)
                                .addGroup(panelInfoEmisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textNombreEmisor)
                                    .addGroup(panelInfoEmisorLayout.createSequentialGroup()
                                        .addComponent(textRFCEmisor, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel43)))))
                        .addGap(18, 18, 18)
                        .addComponent(textRegimenEmisor, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInfoEmisorLayout.setVerticalGroup(
            panelInfoEmisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoEmisorLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInfoEmisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(textNombreEmisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(panelInfoEmisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(textRFCEmisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43)
                    .addComponent(textRegimenEmisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInfoEmisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel41))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInfoEmisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDomFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelExpedidoEn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout panelEmisorLayout = new javax.swing.GroupLayout(panelEmisor);
        panelEmisor.setLayout(panelEmisorLayout);
        panelEmisorLayout.setHorizontalGroup(
            panelEmisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmisorLayout.createSequentialGroup()
                .addComponent(panelInfoEmisor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelEmisorLayout.setVerticalGroup(
            panelEmisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmisorLayout.createSequentialGroup()
                .addComponent(panelInfoEmisor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Emisor", panelEmisor);

        panelReceptor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Receptor");

        textCalleR.setEditable(false);

        textNumExtR.setEditable(false);

        textColoniaR.setEditable(false);

        textLocalidadR.setEditable(false);

        jLabel33.setText("Calle");

        jLabel34.setText("Núm Ext");

        jLabel35.setText("Colonia");

        jLabel36.setText("Localidad");

        jLabel37.setText("CP");

        textCPR.setEditable(false);

        textMunicipioR.setEditable(false);

        textEstadoR.setEditable(false);

        jLabel38.setText("Municipio");

        jLabel39.setText("Estado");

        jLabel40.setText("País");

        textPaisR.setEditable(false);

        javax.swing.GroupLayout panelDomReceptorLayout = new javax.swing.GroupLayout(panelDomReceptor);
        panelDomReceptor.setLayout(panelDomReceptorLayout);
        panelDomReceptorLayout.setHorizontalGroup(
            panelDomReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDomReceptorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDomReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36)
                    .addComponent(jLabel39)
                    .addComponent(jLabel37)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelDomReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDomReceptorLayout.createSequentialGroup()
                        .addComponent(textCalleR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textNumExtR, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textColoniaR)
                    .addComponent(textLocalidadR)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDomReceptorLayout.createSequentialGroup()
                        .addComponent(textCPR, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textMunicipioR, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDomReceptorLayout.createSequentialGroup()
                        .addComponent(textEstadoR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textPaisR, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelDomReceptorLayout.setVerticalGroup(
            panelDomReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDomReceptorLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(panelDomReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCalleR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34)
                    .addComponent(textNumExtR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(panelDomReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textColoniaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addGap(5, 5, 5)
                .addGroup(panelDomReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLocalidadR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addGap(5, 5, 5)
                .addGroup(panelDomReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37)
                    .addGroup(panelDomReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textCPR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel38)
                        .addComponent(textMunicipioR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addGroup(panelDomReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDomReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textEstadoR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel40)
                        .addComponent(textPaisR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel39))
                .addGap(27, 27, 27))
        );

        jLabel71.setText("Nombre");

        jLabel72.setText("RFC");

        textRFCReceptor.setEditable(false);

        textNombreReceptor.setEditable(false);

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel42.setText("Domicilio");

        javax.swing.GroupLayout panelReceptorLayout = new javax.swing.GroupLayout(panelReceptor);
        panelReceptor.setLayout(panelReceptorLayout);
        panelReceptorLayout.setHorizontalGroup(
            panelReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReceptorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelReceptorLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelReceptorLayout.createSequentialGroup()
                        .addGroup(panelReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelDomReceptor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel72)
                            .addGroup(panelReceptorLayout.createSequentialGroup()
                                .addComponent(jLabel71)
                                .addGap(57, 57, 57)
                                .addGroup(panelReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textNombreReceptor)
                                    .addGroup(panelReceptorLayout.createSequentialGroup()
                                        .addComponent(textRFCReceptor, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 216, Short.MAX_VALUE))))
                            .addGroup(panelReceptorLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel42)))
                        .addGap(0, 362, Short.MAX_VALUE))))
        );
        panelReceptorLayout.setVerticalGroup(
            panelReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReceptorLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel71)
                    .addComponent(textNombreReceptor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(panelReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel72)
                    .addComponent(textRFCReceptor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabel42)
                .addGap(11, 11, 11)
                .addComponent(panelDomReceptor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelInfoReceptorLayout = new javax.swing.GroupLayout(panelInfoReceptor);
        panelInfoReceptor.setLayout(panelInfoReceptorLayout);
        panelInfoReceptorLayout.setHorizontalGroup(
            panelInfoReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoReceptorLayout.createSequentialGroup()
                .addComponent(panelReceptor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelInfoReceptorLayout.setVerticalGroup(
            panelInfoReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoReceptorLayout.createSequentialGroup()
                .addComponent(panelReceptor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Receptor", panelInfoReceptor);

        tablaConceptos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaConceptos);

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel44.setText("Lista conceptos");

        javax.swing.GroupLayout panelInfoConceptosLayout = new javax.swing.GroupLayout(panelInfoConceptos);
        panelInfoConceptos.setLayout(panelInfoConceptosLayout);
        panelInfoConceptosLayout.setHorizontalGroup(
            panelInfoConceptosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoConceptosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoConceptosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE)
                    .addGroup(panelInfoConceptosLayout.createSequentialGroup()
                        .addComponent(jLabel44)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelInfoConceptosLayout.setVerticalGroup(
            panelInfoConceptosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoConceptosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel44)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("Conceptos", panelInfoConceptos);

        tablaTraslados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablaTraslados);

        tablaRetenciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tablaRetenciones);

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel45.setText("Retenciones");

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel46.setText("Traslados");

        jLabel61.setText("Total Retenciones");

        textTotalRetenciones.setEditable(false);

        jLabel62.setText("Total Traslados");

        textTotalTraslados.setEditable(false);

        javax.swing.GroupLayout panelInfoImpuestosLayout = new javax.swing.GroupLayout(panelInfoImpuestos);
        panelInfoImpuestos.setLayout(panelInfoImpuestosLayout);
        panelInfoImpuestosLayout.setHorizontalGroup(
            panelInfoImpuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoImpuestosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoImpuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelInfoImpuestosLayout.createSequentialGroup()
                        .addGroup(panelInfoImpuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel45)
                            .addComponent(jLabel46))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoImpuestosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelInfoImpuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoImpuestosLayout.createSequentialGroup()
                                .addComponent(jLabel61)
                                .addGap(18, 18, 18)
                                .addComponent(textTotalRetenciones, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoImpuestosLayout.createSequentialGroup()
                                .addComponent(jLabel62)
                                .addGap(18, 18, 18)
                                .addComponent(textTotalTraslados, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        panelInfoImpuestosLayout.setVerticalGroup(
            panelInfoImpuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoImpuestosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel45)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInfoImpuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel61)
                    .addComponent(textTotalRetenciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelInfoImpuestosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel62)
                    .addComponent(textTotalTraslados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane1.addTab("Impuestos", panelInfoImpuestos);

        jLabel47.setText("UUID");

        jLabel48.setText("Fecha de timbrado");

        jLabel49.setText("Sello CFD");

        jLabel50.setText("Certificado SAT");

        jLabel51.setText("Sello SAT");

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel52.setText("Complemento");

        textUuid.setEditable(false);

        textFechaTimbrado.setEditable(false);

        textSelloCFD.setEditable(false);

        textCertSAT.setEditable(false);

        textSelloSAT.setEditable(false);

        javax.swing.GroupLayout panelComplementoLayout = new javax.swing.GroupLayout(panelComplemento);
        panelComplemento.setLayout(panelComplementoLayout);
        panelComplementoLayout.setHorizontalGroup(
            panelComplementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComplementoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelComplementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel52)
                    .addGroup(panelComplementoLayout.createSequentialGroup()
                        .addGroup(panelComplementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel47)
                            .addComponent(jLabel48)
                            .addComponent(jLabel49)
                            .addComponent(jLabel50)
                            .addComponent(jLabel51))
                        .addGap(29, 29, 29)
                        .addGroup(panelComplementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textSelloSAT)
                            .addComponent(textCertSAT)
                            .addGroup(panelComplementoLayout.createSequentialGroup()
                                .addGroup(panelComplementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFechaTimbrado, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textUuid, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 478, Short.MAX_VALUE))
                            .addComponent(textSelloCFD))))
                .addContainerGap())
        );
        panelComplementoLayout.setVerticalGroup(
            panelComplementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComplementoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel52)
                .addGap(18, 18, 18)
                .addGroup(panelComplementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(textUuid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(panelComplementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(textFechaTimbrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(panelComplementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSelloCFD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel49))
                .addGap(10, 10, 10)
                .addGroup(panelComplementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCertSAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel50))
                .addGap(10, 10, 10)
                .addGroup(panelComplementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSelloSAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel51))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelInfoComplementoLayout = new javax.swing.GroupLayout(panelInfoComplemento);
        panelInfoComplemento.setLayout(panelInfoComplementoLayout);
        panelInfoComplementoLayout.setHorizontalGroup(
            panelInfoComplementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoComplementoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelComplemento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelInfoComplementoLayout.setVerticalGroup(
            panelInfoComplementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoComplementoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelComplemento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Complemento", panelInfoComplemento);

        jLabel21.setText("Información general");

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelInfoGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel21)
                .addGap(4, 4, 4)
                .addComponent(panelInfoGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuArchivo.setText("Archivo");

        menuSeleccionarArchivo.setText("Analizar archivo");
        menuSeleccionarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSeleccionarArchivoActionPerformed(evt);
            }
        });
        menuArchivo.add(menuSeleccionarArchivo);

        menuSeleccionarCarpeta.setText("Seleccionar carpeta");
        menuSeleccionarCarpeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSeleccionarCarpetaActionPerformed(evt);
            }
        });
        menuArchivo.add(menuSeleccionarCarpeta);

        menuListarArchivos.setText("Listar archivos");
        menuListarArchivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListarArchivosActionPerformed(evt);
            }
        });
        menuArchivo.add(menuListarArchivos);

        menuBar.add(menuArchivo);

        menuEditar.setText("Editar");

        menuLimpiar.setText("Limpiar campos");
        menuLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLimpiarActionPerformed(evt);
            }
        });
        menuEditar.add(menuLimpiar);

        menuBar.add(menuEditar);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSeleccionarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSeleccionarArchivoActionPerformed
        JFileChooser jChooser = new JFileChooser();
        jChooser.setCurrentDirectory(new java.io.File("./"));
        jChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        Action detalles = jChooser.getActionMap().get("viewTypeDetails");
        detalles.actionPerformed(null);
        FileNameExtensionFilter xmlfilter = new FileNameExtensionFilter("archivos xml (*.xml)", "xml");
//        FileNameExtensionFilter xsdfilter = new FileNameExtensionFilter("archivos xsd (*.xsd)", "xsd");
//        jChooser.setFileFilter(xsdfilter);
        jChooser.setFileFilter(xmlfilter);
        jChooser.setDialogTitle("Selección de factura");
        int seleccion = jChooser.showOpenDialog(this);
        if( seleccion == JFileChooser.APPROVE_OPTION ){
            File file = jChooser.getSelectedFile();
            if(null != file){
                leerArchivoXMLProcesar(file);
            }
        }
    }//GEN-LAST:event_menuSeleccionarArchivoActionPerformed

    private void menuSeleccionarCarpetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSeleccionarCarpetaActionPerformed
        JFileChooser jChooser = new JFileChooser();
        jChooser.setCurrentDirectory(new java.io.File("./"));
        jChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        Action detalles = jChooser.getActionMap().get("viewTypeDetails");
        detalles.actionPerformed(null);
        jChooser.setDialogTitle("Selección de carpeta de trabajo");
        int seleccion = jChooser.showOpenDialog(this);
        if( seleccion == JFileChooser.APPROVE_OPTION ){
            limpiarCampos();//Se limpian todos los campos
            File folder = jChooser.getSelectedFile();
            if(null != folder){
                LOGGER.info("Se selecciona la carpeta: " + folder.getAbsolutePath());
                DirectoryScanner scanner = new DirectoryScanner();
                scanner.setIncludes(new String[]{"**/*" + Principal.XML_FORMAT});
                scanner.setBasedir(folder);
                scanner.setCaseSensitive(false);
                scanner.scan();
                String[] files = scanner.getIncludedFiles();
                LOGGER.info("Se listan los archivos xml encontrados: " + files.length);
                for (String file : files) {
                    System.out.println(folder.toPath().resolve(file));
                }
            }
        }
    }//GEN-LAST:event_menuSeleccionarCarpetaActionPerformed

    private void menuLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_menuLimpiarActionPerformed

    private void menuListarArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListarArchivosActionPerformed
        JFileChooser jChooser = new JFileChooser();
        jChooser.setCurrentDirectory(new java.io.File("./"));
        jChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        Action detalles = jChooser.getActionMap().get("viewTypeDetails");
        detalles.actionPerformed(null);
        jChooser.setDialogTitle("Selección de carpeta de trabajo");
        int seleccion = jChooser.showOpenDialog(this);
        if( seleccion == JFileChooser.APPROVE_OPTION ){
            File folder = jChooser.getSelectedFile();
            if(null != folder && folder.isDirectory()){
                dialogArchivos.setRutaCarpeta(folder.toPath());
                dialogArchivos.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(this, "No se seleccionó una carpeta", "Carpeta no seleccionada", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_menuListarArchivosActionPerformed
    
    private void leerArchivoXMLProcesar(File file){
        limpiarCampos();//Se limpian todos los campos
        StringBuilder sBuffer = new StringBuilder();
        LOGGER.info("Se selecciona el archivo: " + file.getName());
        BufferedReader br = null;
        FileReader fr = null;
        boolean continuar = false;
        try {
            fr = new FileReader(file.getAbsoluteFile());
            String sCurrentLine;
            br = new BufferedReader(new InputStreamReader(new FileInputStream(file.getAbsolutePath()), "UTF8"));
            while ((sCurrentLine = br.readLine()) != null) {
                sBuffer.append(sCurrentLine);
            }
            continuar = true;
        } catch (IOException e) {
            LOGGER.info("No se leyó el archivo, por favor verificar.");
        } finally {
            try {
                if (br != null) {br.close();}
                if (fr != null) {fr.close();}
            } catch (IOException ex) {}
        }
        if(continuar){
            ProcesarXML proc = new ProcesarXML(sBuffer.toString(), this);
            proc.procesarXML();
        }
    }
    
    public void addDataConceptos(ArrayList<Concepto> datos){
        for (Concepto dato : datos) {
            modelConceptos.addData(dato);
        }
        modelConceptos.fireTableDataChanged();
        tablaConceptos.repaint();
    }
    
    public void addDataRetenciones(ArrayList<Retencion> datos){
        for (Retencion dato : datos) {
            modelRetenciones.addData(dato);
        }
        modelRetenciones.fireTableDataChanged();
        tablaRetenciones.repaint();
    }
    
    public void addDataTraslados(ArrayList<Traslado> datos){
        for (Traslado dato : datos) {
            modelTraslados.addData(dato);
        }
        modelTraslados.fireTableDataChanged();
        tablaTraslados.repaint();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    public void procesarArchivoXML(String file){
        leerArchivoXMLProcesar(new File(file));
    }
    
    public void setLabelVersion(String labelVersion) {
        this.labelVersion.setText(labelVersion);
    }

    public void setTextFechaFolioFiscalOrig(String text) {
        this.textFechaFolioFiscalOrig.setText(text);
    }

    public void setTextFolioFiscalOrig(String text) {
        this.textFolioFiscalOrig.setText(text);
    }

    public void setTextLugarExpedicion(String text) {
        this.textLugarExpedicion.setText(text);
    }

    public void setTextMoneda(String text) {
        this.textMoneda.setText(text);
    }

    public void setTextMontoFolioFiscalOrig(String text) {
        this.textMontoFolioFiscalOrig.setText(text);
    }

    public void setTextSerieFolioFiscalOrig(String text) {
        this.textSerieFolioFiscalOrig.setText(text);
    }

    public void setTextTipoCambio(String text) {
        this.textTipoCambio.setText(text);
    }

    public void setTextcondicionesDePago(String text) {
        this.textcondicionesDePago.setText(text);
    }

    public void setTextdescuento(String text) {
        this.textdescuento.setText(text);
    }

    public void setTextfecha(String text) {
        this.textfecha.setText(text);
    }

    public void setTextfolio(String text) {
        this.textfolio.setText(text);
    }

    public void setTextformaDePago(String text) {
        this.textformaDePago.setText(text);
    }

    public void setTextmetodoDePago(String text) {
        this.textmetodoDePago.setText(text);
    }

    public void setTextserie(String text) {
        this.textserie.setText(text);
    }

    public void setTextsubTotal(String text) {
        this.textsubTotal.setText(text);
    }

    public void setTexttipoDeComprobante(String text) {
        this.texttipoDeComprobante.setText(text);
    }

    public void setTexttotal(String text) {
        this.texttotal.setText(text);
    }

    public void setTextTotalRetenciones(String text) {
        this.textTotalRetenciones.setText(text);
    }

    public void setTextTotalTraslados(String text) {
        this.textTotalTraslados.setText(text);
    }

    public void setTextFechaTimbrado(String text) {
        this.textFechaTimbrado.setText(text);
    }

    public void setTextSelloCFD(String text) {
        this.textSelloCFD.setText(text);
    }

    public void setTextSelloSAT(String text) {
        this.textSelloSAT.setText(text);
    }

    public void setTextUuid(String text) {
        this.textUuid.setText(text);
    }

    public void setTextCertSAT(String text) {
        this.textCertSAT.setText(text);
    }

    public void setTextCalleR(String text) {
        this.textCalleR.setText(text);
    }

    public void setTextColoniaR(String text) {
        this.textColoniaR.setText(text);
    }

    public void setTextEstadoR(String text) {
        this.textEstadoR.setText(text);
    }

    public void setTextLocalidadR(String text) {
        this.textLocalidadR.setText(text);
    }

    public void setTextMunicipioR(String text) {
        this.textMunicipioR.setText(text);
    }

    public void setTextNumExtR(String text) {
        this.textNumExtR.setText(text);
    }

    public void setTextPaisR(String text) {
        this.textPaisR.setText(text);
    }

    public void setTextNombreReceptor(String text) {
        this.textNombreReceptor.setText(text);
    }

    public void setTextRFCReceptor(String text) {
        this.textRFCReceptor.setText(text);
    }

    public void setTextCPR(String text) {
        this.textCPR.setText(text);
    }

    public void setTextCPEx(String text) {
        this.textCPEx.setText(text);
    }

    public void setTextCPF(String text) {
        this.textCPF.setText(text);
    }

    public void setTextCalleEx(String text) {
        this.textCalleEx.setText(text);
    }

    public void setTextCalleF(String text) {
        this.textCalleF.setText(text);
    }

    public void setTextColoniaEx(String text) {
        this.textColoniaEx.setText(text);
    }

    public void setTextColoniaF(String text) {
        this.textColoniaF.setText(text);
    }

    public void setTextEstadoEx(String text) {
        this.textEstadoEx.setText(text);
    }

    public void setTextEstadoF(String text) {
        this.textEstadoF.setText(text);
    }

    public void setTextLocalidadEx(String text) {
        this.textLocalidadEx.setText(text);
    }

    public void setTextLocalidadF(String text) {
        this.textLocalidadF.setText(text);
    }

    public void setTextMunicipioEx(String text) {
        this.textMunicipioEx.setText(text);
    }

    public void setTextMunicipioF(String text) {
        this.textMunicipioF.setText(text);
    }

    public void setTextNombreEmisor(String text) {
        this.textNombreEmisor.setText(text);
    }

    public void setTextNumExtEx(String text) {
        this.textNumExtEx.setText(text);
    }

    public void setTextNumExtF(String text) {
        this.textNumExtF.setText(text);
    }

    public void setTextRFCEmisor(String text) {
        this.textRFCEmisor.setText(text);
    }

    public void setTextRegimenEmisor(String text) {
        this.textRegimenEmisor.setText(text);
    }

    public void setTextPaisF(String text) {
        this.textPaisF.setText(text);
    }

    public void setTextPaisEx(String text) {
        this.textPaisEx.setText(text);
    }
    
    private void limpiarCampos(){
        modelConceptos.emptyData();
        modelConceptos.fireTableDataChanged();
        tablaConceptos.repaint();
        modelRetenciones.emptyData();
        modelRetenciones.fireTableDataChanged();
        tablaRetenciones.repaint();
        modelTraslados.emptyData();
        modelTraslados.fireTableDataChanged();
        tablaTraslados.repaint();
        labelVersion.setText("0.0");
        //Se resetean todos los textfields
        cleanAllTextPanel(panelInfoGeneral);
        cleanAllTextPanel(panelInfoEmisor);
        cleanAllTextPanel(panelDomFiscal);
        cleanAllTextPanel(panelExpedidoEn);
        cleanAllTextPanel(panelReceptor);
        cleanAllTextPanel(panelDomReceptor);
        cleanAllTextPanel(panelInfoImpuestos);
        cleanAllTextPanel(panelComplemento);
    }
    
    private void cleanAllTextPanel(JPanel panel){
        for (Component c : panel.getComponents()){    
            if (c instanceof JTextField){
                ((JTextField) c).setText("");
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelVersion;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JMenuItem menuLimpiar;
    private javax.swing.JMenuItem menuListarArchivos;
    private javax.swing.JMenuItem menuSeleccionarArchivo;
    private javax.swing.JMenuItem menuSeleccionarCarpeta;
    private javax.swing.JPanel panelComplemento;
    private javax.swing.JPanel panelDomFiscal;
    private javax.swing.JPanel panelDomReceptor;
    private javax.swing.JPanel panelEmisor;
    private javax.swing.JPanel panelExpedidoEn;
    private javax.swing.JPanel panelInfoComplemento;
    private javax.swing.JPanel panelInfoConceptos;
    private javax.swing.JPanel panelInfoEmisor;
    private javax.swing.JPanel panelInfoGeneral;
    private javax.swing.JPanel panelInfoImpuestos;
    private javax.swing.JPanel panelInfoReceptor;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelReceptor;
    private javax.swing.JTable tablaConceptos;
    private javax.swing.JTable tablaRetenciones;
    private javax.swing.JTable tablaTraslados;
    private javax.swing.JTextField textCPEx;
    private javax.swing.JTextField textCPF;
    private javax.swing.JTextField textCPR;
    private javax.swing.JTextField textCalleEx;
    private javax.swing.JTextField textCalleF;
    private javax.swing.JTextField textCalleR;
    private javax.swing.JTextField textCertSAT;
    private javax.swing.JTextField textColoniaEx;
    private javax.swing.JTextField textColoniaF;
    private javax.swing.JTextField textColoniaR;
    private javax.swing.JTextField textEstadoEx;
    private javax.swing.JTextField textEstadoF;
    private javax.swing.JTextField textEstadoR;
    private javax.swing.JTextField textFechaFolioFiscalOrig;
    private javax.swing.JTextField textFechaTimbrado;
    private javax.swing.JTextField textFolioFiscalOrig;
    private javax.swing.JTextField textLocalidadEx;
    private javax.swing.JTextField textLocalidadF;
    private javax.swing.JTextField textLocalidadR;
    private javax.swing.JTextField textLugarExpedicion;
    private javax.swing.JTextField textMoneda;
    private javax.swing.JTextField textMontoFolioFiscalOrig;
    private javax.swing.JTextField textMunicipioEx;
    private javax.swing.JTextField textMunicipioF;
    private javax.swing.JTextField textMunicipioR;
    private javax.swing.JTextField textNombreEmisor;
    private javax.swing.JTextField textNombreReceptor;
    private javax.swing.JTextField textNumExtEx;
    private javax.swing.JTextField textNumExtF;
    private javax.swing.JTextField textNumExtR;
    private javax.swing.JTextField textPaisEx;
    private javax.swing.JTextField textPaisF;
    private javax.swing.JTextField textPaisR;
    private javax.swing.JTextField textRFCEmisor;
    private javax.swing.JTextField textRFCReceptor;
    private javax.swing.JTextField textRegimenEmisor;
    private javax.swing.JTextField textSelloCFD;
    private javax.swing.JTextField textSelloSAT;
    private javax.swing.JTextField textSerieFolioFiscalOrig;
    private javax.swing.JTextField textTipoCambio;
    private javax.swing.JTextField textTotalRetenciones;
    private javax.swing.JTextField textTotalTraslados;
    private javax.swing.JTextField textUuid;
    private javax.swing.JTextField textcondicionesDePago;
    private javax.swing.JTextField textdescuento;
    private javax.swing.JTextField textfecha;
    private javax.swing.JTextField textfolio;
    private javax.swing.JTextField textformaDePago;
    private javax.swing.JTextField textmetodoDePago;
    private javax.swing.JTextField textserie;
    private javax.swing.JTextField textsubTotal;
    private javax.swing.JTextField texttipoDeComprobante;
    private javax.swing.JTextField texttipoDeComprobante24;
    private javax.swing.JTextField texttipoDeComprobante25;
    private javax.swing.JTextField texttipoDeComprobante26;
    private javax.swing.JTextField texttipoDeComprobante27;
    private javax.swing.JTextField texttipoDeComprobante28;
    private javax.swing.JTextField texttipoDeComprobante29;
    private javax.swing.JTextField texttipoDeComprobante30;
    private javax.swing.JTextField texttipoDeComprobante31;
    private javax.swing.JTextField texttotal;
    // End of variables declaration//GEN-END:variables
}
